### ISSUE TITLE
yo docker files in source code

### ISSUE THREAD

**Issue by kachkaev** [SteveLasker/polyglot-web-node#1]
Hi Steve,

I came across [your video from DockerCon16](https://www.youtube.com/watch?v=_Y2AI-j6ce0) and here I am exploring this repo.

In your demo the project contains a bunch of files which you generate with `yo docker`. I haven't found them in the source code and they do not appear in `.gitignore` either.

Given you've had some experience with the approach you've been describing in your talk, how would you recommend to organise these files? Shall they be added to the repo or shall new team members just call `yo docker` after `git clone`?

**Comment by SteveLasker** [comment]
Hi Alexander,
There are two branches. The main branch has all the files already added. The pre docker branch is what I used for the demo, with the docker assets not yet added. 
But, yes. Yo docker is the way you would add them to your project. 
Steve

**Comment by kachkaev** [comment]
Ah! I was expecting to see docker files and `.vscode/tasks.json` in the root of the repo. Now all makes sense!
